// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/applications" | "/applications/dnafish" | "/applications/education" | "/applications/flim" | "/applications/fluorescence" | "/applications/histology" | "/applications/labautomation" | "/applications/livecell" | "/applications/multiwell" | "/applications/organoid" | "/applications/remotebsl" | "/blog" | "/blog/[slug]" | "/configurator" | "/contact" | "/imprint" | "/privacy" | "/products/discovery" | "/products/discovery/electronics" | "/products/discovery/fluorescence-laser" | "/products/discovery/fluorescence-led" | "/products/discovery/infinity" | "/products/discovery/light-sheet" | "/products/frame" | "/products/makers" | "/stories/fairscope" | "/stories/flimlabs" | "/stories/photonic-compute" | "/stories/stainstorm" | "/support"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/applications": {}
  "/applications/dnafish": {}
  "/applications/education": {}
  "/applications/flim": {}
  "/applications/fluorescence": {}
  "/applications/histology": {}
  "/applications/labautomation": {}
  "/applications/livecell": {}
  "/applications/multiwell": {}
  "/applications/organoid": {}
  "/applications/remotebsl": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/configurator": {}
  "/contact": {}
  "/imprint": {}
  "/privacy": {}
  "/products/discovery": {}
  "/products/discovery/electronics": {}
  "/products/discovery/fluorescence-laser": {}
  "/products/discovery/fluorescence-led": {}
  "/products/discovery/infinity": {}
  "/products/discovery/light-sheet": {}
  "/products/frame": {}
  "/products/makers": {}
  "/stories/fairscope": {}
  "/stories/flimlabs": {}
  "/stories/photonic-compute": {}
  "/stories/stainstorm": {}
  "/support": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
