// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/dnafish/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/dnafish">> = Specific
  const handler = {} as typeof import("../../src/app/applications/dnafish/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/education/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/education">> = Specific
  const handler = {} as typeof import("../../src/app/applications/education/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/flim/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/flim">> = Specific
  const handler = {} as typeof import("../../src/app/applications/flim/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/fluorescence/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/fluorescence">> = Specific
  const handler = {} as typeof import("../../src/app/applications/fluorescence/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/histology/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/histology">> = Specific
  const handler = {} as typeof import("../../src/app/applications/histology/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/labautomation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/labautomation">> = Specific
  const handler = {} as typeof import("../../src/app/applications/labautomation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/livecell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/livecell">> = Specific
  const handler = {} as typeof import("../../src/app/applications/livecell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/multiwell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/multiwell">> = Specific
  const handler = {} as typeof import("../../src/app/applications/multiwell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/organoid/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/organoid">> = Specific
  const handler = {} as typeof import("../../src/app/applications/organoid/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications">> = Specific
  const handler = {} as typeof import("../../src/app/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/applications/remotebsl/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications/remotebsl">> = Specific
  const handler = {} as typeof import("../../src/app/applications/remotebsl/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/configurator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/configurator">> = Specific
  const handler = {} as typeof import("../../src/app/configurator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../src/app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/imprint/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/imprint">> = Specific
  const handler = {} as typeof import("../../src/app/imprint/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/discovery/electronics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/discovery/electronics">> = Specific
  const handler = {} as typeof import("../../src/app/products/discovery/electronics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/discovery/fluorescence-laser/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/discovery/fluorescence-laser">> = Specific
  const handler = {} as typeof import("../../src/app/products/discovery/fluorescence-laser/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/discovery/fluorescence-led/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/discovery/fluorescence-led">> = Specific
  const handler = {} as typeof import("../../src/app/products/discovery/fluorescence-led/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/discovery/infinity/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/discovery/infinity">> = Specific
  const handler = {} as typeof import("../../src/app/products/discovery/infinity/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/discovery/light-sheet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/discovery/light-sheet">> = Specific
  const handler = {} as typeof import("../../src/app/products/discovery/light-sheet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/discovery/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/discovery">> = Specific
  const handler = {} as typeof import("../../src/app/products/discovery/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/frame/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/frame">> = Specific
  const handler = {} as typeof import("../../src/app/products/frame/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/products/makers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products/makers">> = Specific
  const handler = {} as typeof import("../../src/app/products/makers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stories/fairscope/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories/fairscope">> = Specific
  const handler = {} as typeof import("../../src/app/stories/fairscope/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stories/flimlabs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories/flimlabs">> = Specific
  const handler = {} as typeof import("../../src/app/stories/flimlabs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stories/photonic-compute/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories/photonic-compute">> = Specific
  const handler = {} as typeof import("../../src/app/stories/photonic-compute/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/stories/stainstorm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stories/stainstorm">> = Specific
  const handler = {} as typeof import("../../src/app/stories/stainstorm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
